# Tensors and Key Attributes
### Author: Dr. Yves Staudt
In diesem Notebook stellen wir die Tensoren in Python und deren Attribute dar. Die Ideen dieses Notebooks stammen aus dem Buch von Chollet (2019)

## Loading Packages

In [1]:
import pandas as pd
import numpy as np
import os
import tensorflow as tf
from tensorflow import keras

## 0D Tensor - Scalar

In einem ersten Schritt erstellen wir den Tensor mithilfe von numpy.

In [2]:
x = np.array(12)
x

array(12)

Mithilfe des folgenden Befehls können wir Anzahl der Axen number of axes) (des Skalars angeben

In [3]:
x.ndim

0

Wir beobachten, dass der Tensor 0 Achsen hat.
Nun interessieren wir uns für die Form (shape) des Tensors

In [4]:
x.shape

()

Ein Skalar hat auch keine Dimensionen, wie hier mit der `shape` Funktion dargestellt.
Die letzte Eigenschaft ist der Datentyp (data type):

In [5]:
x.dtype

dtype('int32')

Unser Skalar enthält eine ganze Zahl des Formats `int64`.

## 1D Tensor - Vectors
In einem ersten Schritt erstellen wir den 1D Tensor mit Numpy.

In [6]:
y = np.array([12, 3, 6, 14])

In einem weiteren Schritt schauen wir die Eigenschaften des Tensors an.
Zuerst starten wir mit den Achsen.

In [26]:
y

array([12,  3,  6, 14])

In [7]:
y.ndim

1

Unser Vektor hat eine Achse.
Die zweite Eigenschaft ist die Form.

In [8]:
y.shape

(4,)

Unser Vektor besteht aus vier Einträgen.
Die letzte Eigenschaft ist der Datentyp.

In [27]:
x.dtype

dtype('int32')

Unser Vektor besteht aus ganzen Zahl des Formats `int64`.

## 2D Tensor - Matrices
In einem ersten Schritt erstellen wir die Matrix mithilfe von `numpy`.

In [10]:
z = np.array([[5, 78, 2, 34, 0],
              [6, 79, 3, 35, 1],
              [7, 80, 4, 36, 2]])

Nun schauen wir uns die Eigenschaften der Matrix an.
Wir starten mit den Achsen.

In [28]:
z

array([[ 5, 78,  2, 34,  0],
       [ 6, 79,  3, 35,  1],
       [ 7, 80,  4, 36,  2]])

In [11]:
z.ndim

2

Unsere Matrix hat zwei Achsen, die Zeilen und Spalten.
Nun schauen wir uns die Dimension der jeweiligen Achsen an.

In [12]:
z.shape

(3, 5)

Unsere Matrix hat drei Zeilen und fünf Spalten.
Das format der Matrix besteht aus ganzen Zahlen des Formats `int64` wie hier aufgezeigt.

In [13]:
z.dtype

dtype('int32')

## 3D Tensor
Wir erstellen nun eine 3D Tensor mithilfe von `numpy` indem wir die Matrix von oben in einen neuen `array` einbetten.

In [14]:
t = np.array([[[5, 78, 2, 34, 0],
              [6, 79, 3, 35, 1],
              [7, 80, 4, 36, 2]],
              [[5, 78, 2, 34, 0],
              [6, 79, 3, 35, 1],
              [7, 80, 4, 36, 2]],
              [[5, 78, 2, 34, 0],
              [6, 79, 3, 35, 1],
              [7, 80, 4, 36, 2]]])

Nun schauen wir uns die Eigenschaften des 3D Tensor.
Wir starten mit der Anzahl Achsen.

In [29]:
t

array([[[ 5, 78,  2, 34,  0],
        [ 6, 79,  3, 35,  1],
        [ 7, 80,  4, 36,  2]],

       [[ 5, 78,  2, 34,  0],
        [ 6, 79,  3, 35,  1],
        [ 7, 80,  4, 36,  2]],

       [[ 5, 78,  2, 34,  0],
        [ 6, 79,  3, 35,  1],
        [ 7, 80,  4, 36,  2]]])

In [15]:
t.ndim

3

Unser 3D Tensor hat wie erwartet 3 Achsen.
Nun schauen wir uns die Dimensionen der jeweiligen Achsen an.

In [16]:
t.shape

(3, 3, 5)

Unser 3D Tensor hat 3 Proben (samples) mit einer Eigenschaft von 3 Zeilen und 5 Spalten.
Der 3D Tensor besteht aus ganzen Zahlen mit dem Foramt `int64`.

In [17]:
t.dtype

dtype('int32')

## MNIST Datensatz
In diesem Abschnitt schauen wir uns an, wie die Formaten des bekannten MNIST Datensatzes sind.
Zuerst laden wir die Daten.

In [18]:
from keras.datasets import mnist
# load dataset
(x_train, y_train),(x_test, y_test) = mnist.load_data()

In [19]:
print("Der Trainings Datensatz hat folgende Anzahl von Achsen: {}".format(x_train.ndim))
print("Der Test Datensatz hat folgende Anzahl von Achsen: {}".format(x_test.ndim))
print("Die Zielvarialbe des Training Datensatz hat folgende Anzahl von Achsen: {}".format(y_train.ndim))
print("Die Zielvarialbe des Training Datensatz hat folgende Anzahl von Achsen: {}".format(y_test.ndim))

Der Trainings Datensatz hat folgende Anzahl von Achsen: 3
Der Test Datensatz hat folgende Anzahl von Achsen: 3
Die Zielvarialbe des Training Datensatz hat folgende Anzahl von Achsen: 1
Die Zielvarialbe des Training Datensatz hat folgende Anzahl von Achsen: 1


Die Datensätze `x_train` und `x_test` sind 3D Tensoren, welches unser Erwartung von Bilder entspricht.
Die Datensätze `y_train` und `y_test` welche unsere Zielvariablen enthalten, entsprechen wie erwartet einem Vektor.

In eine weitern Schritt können wir uns noch die Dimensionen pro Achse und das Datenformat anschauen. Hier begrenzen wir uns auf dem Datensatz `x_train`.

In [20]:
print("Der Training Datensatz hat folgende Anzahl Dimensionen entlang der jeweiligen Achsen: {}".format(x_train.shape))
print("Der Training Datensatz hat folgenden Datentyp: {}".format(x_train.ndim))

Der Training Datensatz hat folgende Anzahl Dimensionen entlang der jeweiligen Achsen: (60000, 28, 28)
Der Training Datensatz hat folgenden Datentyp: 3


## Tensors Manipulating
Spezifische Elemente in einem Tensor auszuwählen heisst auf Englisch "tensor slicing".
In dem folgenden Coden wollen wir die Zahlenproben 10 bis 1000 auswählen und sie in einem `array` speichern.

In [21]:
my_slice = x_train[10:100] #tensor slicing
print("Die Dimensionen entlang der Achsen der Auslese ist: {}".format(my_slice.shape))

Die Dimensionen entlang der Achsen der Auslese ist: (90, 28, 28)


Folgende beide Befehle mit genaueren Angaben ergeben das gleiche Resultat.

In [22]:
my_slice = x_train[10:100, : , : ]
print("Die Dimensionen entlang der Achsen der Auslese ist: {}".format(my_slice.shape))

Die Dimensionen entlang der Achsen der Auslese ist: (90, 28, 28)


In [23]:
my_slice = x_train[10:100, 0:28, 0:28]
print("Die Dimensionen entlang der Achsen der Auslese ist: {}".format(my_slice.shape))

Die Dimensionen entlang der Achsen der Auslese ist: (90, 28, 28)


Auslesen sind nicht nur möglich entlang der ersten Achse, sondern auch entlang der anderen. Ich kann zum Beispiel auch für meine Bilder nur 14x14 Pixel auswählen. Hier sind zwei Beispiel welche solche Reusltaten generieren.

In [24]:
my_slice = x_train[: , 14: , 14: ]
print("Die Dimensionen entlang der Achsen der Auslese ist: {}".format(my_slice.shape))

Die Dimensionen entlang der Achsen der Auslese ist: (60000, 14, 14)


In [25]:
my_slice = x_train[: , 7:-7 , 7:-7 ]
print("Die Dimensionen entlang der Achsen der Auslese ist: {}".format(my_slice.shape))

Die Dimensionen entlang der Achsen der Auslese ist: (60000, 14, 14)


## References
- Francois Chollet (2018), Deep Learning with Keras, Manning.